name: Build Release Files

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: 'stable'
          cache: true

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          python-version: '3.12'
          activate-environment: rime

      - name: build
        run: |
          go build -C hao_gen -o ../deploy/generator

      - name: generate
        env:
          REF_NAME: ${{ github.ref_name }}
          SHELL: /bin/zsh
        shell: bash -l {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh lua5.4
          touch ~/.zshrc
          chmod +x deploy/deploy_hao.sh
          mkdir -p deploy/hao schemas/releases schemas/hao
          wget -O schemas/hao/wanxiang-lts-zh-hans.gram https://huggingface.co/hertz-hwang/amz-v1-5-zh-hans/resolve/main/wanxiang-lts-zh-hans.gram
          conda activate rime
          lua ./table/gen_freq.lua ./table/freq_simp.txt ./table/freq_simp.txt 9:1 > ./deploy/hao/freq.txt
          lua ./table/gen_freq.lua ./table/freq_trad.txt ./table/freq_trad.txt 9:1 > ./deploy/hao/freq_tc.txt
          ./deploy/deploy_hao.sh
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: schemas/releases/hao-${{ github.ref_name }}.tar.zst
          make_latest: 'true'